--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: exercise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS public.exercise (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    primary_muscle character varying(255) NOT NULL,
    description character varying(255),
    equipment character varying(255),
    secondary_muscle character varying(255)
);


ALTER TABLE public.exercise OWNER TO postgres;

--
-- Name: exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: exercise; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercise (id, name, primary_muscle, description, equipment, secondary_muscle) FROM stdin;
2	dumbbell bench press	chest	\N	\N	\N
4	Barbell Curl	bicep	A classic biceps exercise performed with a barbell.	Barbell	forearm
5	Dumbbell Curl	bicep	A versatile biceps exercise using dumbbells.	Dumbbell	forearm
6	Hammer Curl	bicep	Targets the biceps and forearms with a neutral grip.	Dumbbell	brachialis
7	Concentration Curl	bicep	Isolates the biceps for maximum contraction.	Dumbbell	\N
8	Preacher Curl	bicep	Performed on a preacher bench to isolate the biceps.	Barbell	\N
9	Cable Curl	bicep	Provides constant tension throughout the movement.	Cable Machine	forearm
10	Chin-Up	bicep	A compound exercise that targets the biceps and back.	Bodyweight	back
11	Incline Dumbbell Curl	bicep	Performed on an incline bench for a greater stretch.	Dumbbell	\N
12	EZ-Bar Curl	bicep	Reduces wrist strain while targeting the biceps.	EZ-Bar	forearm
13	Pull-Up	back	A compound exercise that targets the upper back and biceps.	Bodyweight	bicep
14	Lat Pulldown	back	Performed on a cable machine to target the latissimus dorsi.	Cable Machine	bicep
15	Bent-Over Barbell Row	back	A strength exercise focusing on the middle back and lats.	Barbell	bicep
16	Seated Cable Row	back	Targets the middle back using a seated cable row machine.	Cable Machine	bicep
17	Single-Arm Dumbbell Row	back	Isolates each side of the back for balanced development.	Dumbbell	bicep
18	T-Bar Row	back	A rowing movement that targets the middle and upper back.	T-Bar	bicep
19	Deadlift	back	A compound lift that works the entire posterior chain, especially the back.	Barbell	glutes
20	Face Pull	back	Targets the upper back and rear deltoids.	Cable Machine	shoulder
21	Inverted Row	back	A bodyweight exercise that targets the upper and middle back.	Bodyweight	bicep
22	Barbell Bench Press	chest	A classic compound movement for building chest strength and size.	Barbell	tricep
23	Dumbbell Bench Press	chest	Allows for a greater range of motion and chest activation.	Dumbbell	tricep
24	Incline Bench Press	chest	Targets the upper portion of the chest.	Barbell	shoulder
25	Decline Bench Press	chest	Emphasizes the lower chest muscles.	Barbell	tricep
26	Chest Fly	chest	Isolates the chest muscles with a wide arc movement.	Dumbbell	shoulder
27	Push-Up	chest	A bodyweight exercise that targets the chest and triceps.	Bodyweight	tricep
28	Cable Crossover	chest	Provides constant tension for chest development.	Cable Machine	shoulder
29	Pec Deck Machine	chest	A machine-based fly movement for chest isolation.	Machine	shoulder
30	Overhead Press	shoulder	A compound movement that targets the entire shoulder region.	Barbell	tricep
31	Dumbbell Shoulder Press	shoulder	Allows for a greater range of motion and shoulder activation.	Dumbbell	tricep
32	Lateral Raise	shoulder	Isolates the lateral deltoid for width.	Dumbbell	\N
33	Front Raise	shoulder	Targets the anterior deltoid.	Dumbbell	\N
34	Rear Delt Fly	shoulder	Focuses on the rear deltoids and upper back.	Dumbbell	upper back
35	Arnold Press	shoulder	A variation of the shoulder press that hits all three deltoid heads.	Dumbbell	tricep
36	Face Pull	shoulder	Targets the rear deltoids and upper back.	Cable Machine	upper back
37	Upright Row	shoulder	Works the shoulders and upper traps.	Barbell	trapezius
38	Barbell Squat	leg	A fundamental compound movement for overall leg development.	Barbell	glute
39	Leg Press	leg	Targets the quadriceps, hamstrings, and glutes using a leg press machine.	Machine	glute
40	Lunge	leg	A unilateral exercise that works the entire leg and glutes.	Dumbbell	glute
41	Leg Extension	leg	Isolates the quadriceps muscles.	Machine	\N
42	Leg Curl	leg	Isolates the hamstrings.	Machine	\N
43	Romanian Deadlift	leg	Focuses on the hamstrings and glutes.	Barbell	glute
44	Calf Raise	leg	Targets the calf muscles.	Machine	calf
45	Bulgarian Split Squat	leg	A single-leg squat variation for quads and glutes.	Dumbbell	glute
46	Goblet Squat	leg	A squat variation performed with a dumbbell held at the chest.	Dumbbell	glute
47	Crunch	abs	A classic abdominal exercise performed lying on your back.	Bodyweight	\N
48	Plank	abs	An isometric core exercise that targets the abs and lower back.	Bodyweight	back
49	Hanging Leg Raise	abs	Targets the lower abs by raising the legs while hanging.	Pull-Up Bar	hip flexor
50	Russian Twist	abs	A rotational movement that targets the obliques and abs.	Bodyweight	oblique
51	Bicycle Crunch	abs	A dynamic exercise that works the abs and obliques.	Bodyweight	oblique
52	Cable Crunch	abs	Uses a cable machine to add resistance to the crunch movement.	Cable Machine	\N
53	Mountain Climber	abs	A cardio and core exercise performed in a plank position.	Bodyweight	shoulder
54	Ab Wheel Rollout	abs	A challenging core exercise using an ab wheel.	Ab Wheel	back
\.


--
-- Name: exercise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.exercise_id_seq', 54, true);


--
-- Name: exercise exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT exercise_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

