DROP TABLE IF EXISTS public.exercise CASCADE;

CREATE TABLE public.exercise (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    primary_muscle character varying(255) NOT NULL,
    description character varying(255),
    equipment character varying(255),
    secondary_muscle character varying(255)
);

ALTER TABLE public.exercise OWNER TO postgres;

ALTER TABLE public.exercise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT exercise_pkey PRIMARY KEY (id);

SELECT pg_catalog.setval('public.exercise_id_seq', 54, true);